server:
  port: 80

spring:
  application:
    name: cloud-consumer-hystrix-payment

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

#下面连续三个的超时时间，配置了就好了，单位都是毫秒
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ReadTimeout: 10000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 10000

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000

#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000   #设置调用者等待命令执行的超时限制，超过此时间，HystrixCommand被标记为TIMEOUT，并执行回退逻辑
      circuitBreaker:
        requestVolumeThreshold: 200     #设置在一个滚动窗口中，打开断路器的最少请求数
        sleepWindowInMilliseconds: 5000 #设置在回路被打开，拒绝请求到再次尝试请求并决定回路是否继续打开的时间
        errorThresholdPercentage: 50    #设置打开回路并启动回退逻辑的错误比率
  threadpool:
    default:
      coreSize: 200                    #核心线程数
      maxQueueSize: 200               #最大队列数
